import React from "react";
import MainLayout from "../layout/MainLayout";
import SubNetworkImage from "../assets/subnetwork-example.png";

export default function FAQPage() {
  return (
    <div>
      <MainLayout>
        <div className="main-layout-body">
          <div className="about-body">
            <h2 className="about-title">Frequently Asked Questions</h2>
            <h3>What is ProteinWeaver?</h3>
            <p>
              ProteinWeaver is a tool designed to help biologists answer
              questions related to how proteins are connected to other proteins
              with a specific biological process.
            </p>
            <h3>What can I do with this tool?</h3>
            <div className="faq-image-container">
              <p className="about-body-text">
                Suppose you are interested in a particular protein, and you want
                to know how this protein is connected to other proteins that is
                annotated with a biological process (
                <a className="about-body-link" href="https://geneontology.org/docs/ontology-documentation/">
                  GO terms
                </a>
                ). ProteinWeaver will generate an induced subgraph that connects
                your protein of interest to these other proteins. The subnetwork
                is generated by doing a{" "}
                <a className="about-body-link" href="https://neo4j.com/docs/graph-data-science/current/algorithms/yens/">
                  Yen's shortest path algorithm
                </a>{" "}
                for <em>k</em> number of shortest paths.
              </p>
              <img className="subnetwork-image"src={SubNetworkImage}></img>
            </div>
          </div>
        </div>
      </MainLayout>
    </div>
  );
}
