import React from "react";
import MainLayout from "../layout/MainLayout";
import SubNetworkImage from "../assets/subnetwork-example.png";
import Neo4jImage from "../assets/neo4j-image.png";
import InducedSubgraph from "../assets/induced-subgraph.png";


export default function FAQPage() {
  return (
    <div>
      <MainLayout>
        <div className="main-layout-body">
          <div className="faq-body">
            <h2 className="faq-title">Frequently Asked Questions</h2>
            <h3>What is ProteinWeaver?</h3>
            <p>
              ProteinWeaver is a tool designed to help biologists answer
              questions related to how proteins are connected to other proteins
              with a specific biological process.
            </p>
            <h3>What can I do with this tool?</h3>
            <div className="faq-image-container">
              <div>
                <p className="faq-body-text">
                  Suppose you are interested in a particular protein, and you
                  want to know how this protein is connected to other proteins
                  that is annotated with a biological process (
                  <a
                    className="faq-body-link"
                    href="https://geneontology.org/docs/ontology-documentation/"
                  >
                    GO terms
                  </a>
                  ). ProteinWeaver will generate an induced subgraph that
                  connects your protein of interest to these other proteins. The
                  subnetwork is generated by doing a{" "}
                  <a
                    className="faq-body-link"
                    href="https://neo4j.com/docs/graph-data-science/current/algorithms/yens/"
                  >
                    Yen's shortest path algorithm
                  </a>{" "}
                  for <em>k</em> number of shortest paths.
                </p>
                <h3 className="faq-body-text">
                  How can this be useful for biologists?
                </h3>
                <p className="faq-body-text">
                  Proteins with a suspected or known biological functions are
                  often annotated to gene ontology terms (GO terms). These terms
                  represent a biological processes, structurs and functions that
                  a protein may be have. ProteinWeaver can be used to generate
                  hypotheses about the function of a protein of interest based
                  on its connections to other proteins with known functions.
                  Case studies from biochemistry, cell biology, and developmental
                  biology, based on elucidating the connections between proteins
                  and specific pathways and processes, highlight the potential of
                  ProteinWeaver to quickly generate hypotheses for experimental
                  validation.
                </p>
              </div>
              <img className="subnetwork-image" src={SubNetworkImage}></img>
            </div>
            <h3>How does this tool work behind the scenes?</h3>
            <div className="faq-image-container">
              <div>
                <p className="faq-body-text">
                  Thanks to React.js and Cytoscape.js, the frontend of the site
                  works in a fluid and dynamic fashion. Components can be
                  dynamically rendered and in-between page navigation requires
                  no refresh.
                </p>
                <p className="faq-body-text">
                  Due to the complex nature of the networks, a traditional
                  relational database does not provide easy lookups within the
                  network (such as quickly looking up the path between two nodes
                  or get all the nodes with a particular property). From this,
                  we utilized Neo4j, a native graph database. Built for complex
                  networks, Neo4j is able to do graph traversals, shortest path
                  computations, and node lookups extremely fast.
                </p>
              </div>
              <img className="subnetwork-image" src={Neo4jImage}></img>
            </div>
            <h3>What is an "induced subgraph?"</h3>
            <div className="faq-image-container">
              <div>
                <p className="faq-body-text">
                  ProteinWeaver uses a <em>k</em>-shortest path algorithm to generate
                  the queried subnetwork. Interactions may exist between the proteins
                  in the subnetwork that are not directly on the shortest path from
                  the queried protein to proteins annotated to GO terms. In order to provide
                  the full context of the protein of interest and the subnetwork generated,
                  ProteinWeaver also returns any existing interaction between any protein
                  on the subnetwork AKA the "induced subgraph." ProteinWeaver represents
                  these interactions in grey on the graph and gives users the ability
                  to hide or show these edges.
                </p>
              </div>
              <img className="induced-subgraph-image" src={InducedSubgraph}></img>
            </div>
          </div>
        </div>
      </MainLayout>
    </div>
  );
}
