---
title: "Zebrafish Data Processing and Mergin"
author: "Oliver F. Anderson"
date: "2023-10-27"
output: html_document
---

**Zebrafish Data Merging and Wrangling Documentation**
Initialize the work environment.
```{r}
setwd('~/Desktop/neo4j-test/zfish_data/')
library(tidyverse)
```

Next process the data from PsicQuic into a nice format.
```{r}
# get interactor data from PsicQuic
psicquic_interactors <- read_csv("interactors.csv")

# how many unique interactors? not very many...
length(unique(psicquic_interactors$ID))

# make sure that there are no missing values
psicquic_interactors <- subset(psicquic_interactors, !is.na(ID))

psicquic_interactors <- psicquic_interactors %>% distinct(ID, .keep_all = TRUE)

psicquic_interactors <- psicquic_interactors[,c(1,2,13,15,18,19)]

colnames(psicquic_interactors) <- c("ID", "shortLabel",
                                    "primaryRefDb", "primaryRefId",
                                    "secondaryRefDb", "secondaryRefId")

# it appears we are missing two values, let's manually find these since there are only 2
# subset(psicquic_interactors, is.na(uniprotId))
psicquic_interactors$uniprotId <- case_when(
    psicquic_interactors$primaryRefDb == "uniprotkb" ~ psicquic_interactors$primaryRefId,
    psicquic_interactors$secondaryRefDb == "uniprotkb" ~ psicquic_interactors$secondaryRefId,
    psicquic_interactors$shortLabel == "EBI-2213356" ~ "Q2YDS1",
    psicquic_interactors$shortLabel == "EBI-1536909" ~ "A2A121"
  )


psicquic_interactorsIDs <- psicquic_interactors %>% select(ID, uniprotId)

# get interaction data from PsicQuic
psicquic_interactions <- read_csv("interactions.csv")
# change names to more readable ones
colnames(psicquic_interactions) <- c("ID", "InteractorRef1", "InteractorRef2")

# first join the IDs for Ref1
psicquic_interactome <- left_join(psicquic_interactions, psicquic_interactorsIDs, by = c("InteractorRef1" = "ID"), relationship="many-to-many")

# then join the IDs for Ref2
psicquic_interactome <- left_join(psicquic_interactome, psicquic_interactorsIDs, by = c("InteractorRef2" = "ID"), relationship="many-to-many")

colnames(psicquic_interactome) <- c("interactionID", "InteractorRef1", "InteractorRef2", 'uniprotID1', "uniprotID2")

# extract only the necessary information
psicquic_interactome <- 
  psicquic_interactome %>% 
  select(uniprotID1, uniprotID2) %>%
  mutate(source = "psicquic")
```

Save the PsicQuic data to a separate file
```{r}
write_csv(psicquic_interactome, "./zfish_psicquic_results.csv")
```


The next step is to process the data from String-DB.
```{r}
# read the file in
string_db_interactome <- read_delim("stringdb-zfish-interactome.txt", delim = " ")

# get only the data from String-DB that has experimental evidence
string_db_interactome <- string_db_interactome %>% filter(experiments > 0)

# select only the relevant information
string_db_interactome <- string_db_interactome %>% select(protein1, protein2)

# get the mapping data to get uniprot aliases
string_db_names <- read_tsv("7955.protein.aliases.v12.0.txt")

string_db_names <- string_db_names %>%
  filter(source == "UniProt_AC") %>% 
  select(string_protein_id, alias)

# join the uniprot IDs for protein1
string_db_interactome <- left_join(string_db_interactome, string_db_names, by = c("protein1" = "string_protein_id"), relationship = "many-to-many")

# join the uniprot IDs for protein2
string_db_interactome <- left_join(string_db_interactome, string_db_names, by = c("protein2" = "string_protein_id"), relationship = "many-to-many")

# rename the columns to prepare to merge datasets
colnames(string_db_interactome) <- c("protein1", "protein2", "uniprotID1", "uniprotID2")

# extract only the relevant information
string_db_interactome <- 
  string_db_interactome %>%
  select(uniprotID1, uniprotID2) %>%
  mutate(source = "string-db")
```

Now, merge the PsicQuic and String-DB interactomes together.
```{r}
zfish_interactome <- rbind(string_db_interactome, psicquic_interactome)
```

```{r}
write_tsv(zfish_interactome, "./temp_zfish_interactome.txt")
```

```{r}
common_names <- read_tsv("zebrafish_uniprot_mapper.tsv")

common_names <- common_names %>% select(Entry, `Protein names`)

zfish_interactome <- inner_join(zfish_interactome, common_names, by = c("uniprotID1" = "Entry"))

zfish_interactome <- inner_join(zfish_interactome, common_names, by = c("uniprotID2" = "Entry"))

colnames(zfish_interactome) <- c("uniprotID1", "uniprotID2", "source","alt_name1", "alt_name2")

deleted_interactions <- zfish_interactome %>% filter(alt_name1 == "deleted") %>% filter(alt_name2 == "deleted")

zfish_interactome <- zfish_interactome %>% filter(alt_name1 != "deleted") %>% filter(alt_name2 != "deleted")

zfish_interactome <- zfish_interactome %>% mutate(name1 = str_extract(alt_name1, "^[^(]*"),
                             name2 = str_extract(alt_name2, "^[^(]*"))
```


```{r}
write_tsv(zfish_interactome, "./zfish_interactome.txt")
```

```{r}
uniprotIDs <- unique(c(zfish_interactome$uniprotID1, zfish_interactome$uniprotID2))


write_csv(as_tibble(uniprotIDs), "./zfish_uniprotIDs.txt")
```


